import type { Metadata } from 'next';
import { Actor, Silkscreen } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const actor = Actor({ subsets: ['latin'], weight: '400' });
const titan = Silkscreen({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={titan.className}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
